// <auto-generated />
using System;
using EfCore.Core.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EfCore.Core.Migrations
{
    [DbContext(typeof(CustomContext))]
    [Migration("20240909214309_add_person_name")]
    partial class add_person_name
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("EfCore.Core.Entities.Dream", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<bool?>("CanPunch")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Theme")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Dreams");
                });

            modelBuilder.Entity("EfCore.Core.Entities.Person", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("DreamId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("DreamId");

                    b.ToTable("Peoples");
                });

            modelBuilder.Entity("EfCore.Core.Entities.Sleep", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("SleptAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("WokeupAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("PersonId");

                    b.ToTable("Sleeps");
                });

            modelBuilder.Entity("EfCore.Core.Entities.Person", b =>
                {
                    b.HasOne("EfCore.Core.Entities.Dream", "Dream")
                        .WithMany("Peoples")
                        .HasForeignKey("DreamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dream");
                });

            modelBuilder.Entity("EfCore.Core.Entities.Sleep", b =>
                {
                    b.HasOne("EfCore.Core.Entities.Person", "Person")
                        .WithMany("Sleeps")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("EfCore.Core.Entities.NoiseDuringSleep", "Noise", b1 =>
                        {
                            b1.Property<Guid>("SleepId")
                                .HasColumnType("char(36)");

                            b1.Property<bool>("HasNoiseAtKitchen")
                                .HasColumnType("tinyint(1)");

                            b1.HasKey("SleepId");

                            b1.ToTable("Sleeps");

                            b1.WithOwner()
                                .HasForeignKey("SleepId");
                        });

                    b.OwnsMany("EfCore.Core.Entities.Sheep", "CountOfSheeps", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("char(36)");

                            b1.Property<uint>("Name")
                                .HasColumnType("int unsigned")
                                .HasColumnName("SheepName");

                            b1.Property<uint>("Number")
                                .HasColumnType("int unsigned")
                                .HasColumnName("SheepNumber");

                            b1.Property<Guid>("SleepId")
                                .HasColumnType("char(36)");

                            b1.HasKey("Id");

                            b1.HasIndex("SleepId");

                            b1.ToTable("Sheep");

                            b1.WithOwner()
                                .HasForeignKey("SleepId");
                        });

                    b.Navigation("CountOfSheeps");

                    b.Navigation("Noise");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("EfCore.Core.Entities.Dream", b =>
                {
                    b.Navigation("Peoples");
                });

            modelBuilder.Entity("EfCore.Core.Entities.Person", b =>
                {
                    b.Navigation("Sleeps");
                });
#pragma warning restore 612, 618
        }
    }
}
